---

- name: "Check if percona-server is installed"
  shell: dpkg -l | grep -i percona-server-server
  failed_when: false
  changed_when: false
  check_mode: false
  register: percona_server_is_installed
