---

- name: "Check if /root/.my.cnf file exists"
  stat:
    path: "/root/.my.cnf"
  register: root_my_cnf_stat

- name: "Copy .my.cnf file into the root home folder after initial root password changed"
  template:
    src: root-my-cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0600
  when:
    - root_my_cnf_stat.stat.exists == False

- name: "Set the root password"
  mysql_user:
    name: root
    host: "{{ item }}"
    password: "{{ mysql_root_password }}"
    check_implicit_admin: yes
    state: present
    login_unix_socket: "{% if ansible_os_family in ['RedHat', 'Rocky'] %}/var/lib/mysql/mysql.sock{% else %}/var/run/mysqld/mysqld.sock{% endif %}"

  with_items:
    - "{{ ansible_hostname }}"
    - "127.0.0.1"
    - "::1"
    - "localhost"

- name: "Ensure anonymous users are not in the database"
  mysql_user:
    name: ''
    host: "{{ item }}"
    state: absent
    login_unix_socket: "{% if ansible_os_family in ['RedHat', 'Rocky'] %}/var/lib/mysql/mysql.sock{% else %}/var/run/mysqld/mysqld.sock{% endif %}"
  with_items:
    - "{{ ansible_hostname }}"
    - "localhost"

- name: "Remove the test database"
  mysql_db:
    name: test
    state: absent
